title: Yoonhee Gil # your name (or website title) here
logo: "/images/pfp.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters in Convergence IT Engineering, POSTECH 
  <br><br>
  B.S. in Electrical Engineering, POSTECH 
  <br><br>
  <a href="https://www.linkedin.com/in/%EC%9C%A4%ED%9D%AC-%EA%B8%B8-5ba485163/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
